"""Application configuration. Loads .env; no secrets live in source (CLAUDE.md)."""

import os
from dataclasses import dataclass
from functools import lru_cache

from dotenv import load_dotenv

# Feedback prose is generated by a pluggable provider (see feedback/generate.py).
# The default needs no LLM, no key, and no external service.
DEFAULT_FEEDBACK_PROVIDER = "template"
VALID_FEEDBACK_PROVIDERS = ("template", "ollama", "anthropic")


@dataclass(frozen=True)
class Settings:
    database_url: str
    jwt_secret: str
    port: int
    feedback_provider: str
    ollama_url: str
    ollama_model: str
    # Optional: only needed when feedback_provider == "anthropic".
    anthropic_api_key: str


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Load settings from the environment (and backend/.env if present).

    Raises a clear error for missing required values rather than failing later
    with a confusing downstream exception. ANTHROPIC_API_KEY is NOT required -
    it is only used by the optional 'anthropic' feedback provider.
    """
    load_dotenv()

    missing: list[str] = []

    def require(name: str) -> str:
        value = os.environ.get(name, "")
        if not value:
            missing.append(name)
        return value

    feedback_provider = os.environ.get("FEEDBACK_PROVIDER", DEFAULT_FEEDBACK_PROVIDER).strip()
    if feedback_provider not in VALID_FEEDBACK_PROVIDERS:
        raise RuntimeError(
            f"FEEDBACK_PROVIDER must be one of {VALID_FEEDBACK_PROVIDERS}, got '{feedback_provider}'"
        )

    settings = Settings(
        database_url=require("DATABASE_URL"),
        jwt_secret=require("JWT_SECRET"),
        port=int(os.environ.get("PORT", "8080")),
        feedback_provider=feedback_provider,
        ollama_url=os.environ.get("OLLAMA_URL", "http://localhost:11434"),
        ollama_model=os.environ.get("OLLAMA_MODEL", "qwen2.5:7b"),
        anthropic_api_key=os.environ.get("ANTHROPIC_API_KEY", ""),
    )
    if missing:
        raise RuntimeError(
            f"Missing required environment variables: {', '.join(missing)}. "
            "Copy backend/.env.example to backend/.env and fill in the values."
        )
    return settings
